### PR TITLE
Recreated docs website

### PR DESCRIPTION
**Pull request by contawo**
Screenshot from 2024-05-29 09-52-04

# Overview

I have been using this package for one of my projects, and it has performed exceptionally well compared to others. I am very interested in it and want to contribute to this project to help maintain and improve it. My goal is to see this project widely adopted by developers everywhere.

## To the Developer

You have done an excellent job creating this project. I have great respect for your work.

## Changes

I have updated the UI for the documentation website. Here is how it looks with the new update:
Screenshot from 2024-05-29 09-12-38

### Key Changes

- Revamped the overall look of the website.
- Retained the website's red color theme.
- Added more information to the documentation while maintaining the project's standards.
- Integrated SEO features from the previous documentation website.

## Technologies Used

I aimed to use minimal technologies to achieve the desired results:

1. **Tailwind CSS** for styling the application.
2. **Nextra** for the documentation user interface.
3. **Next.js 14**, using the `pages` router as required by Nextra.

## Challenges Faced and Solutions

- **Challenge:** Embedding the `demo` or `playground` into Nextra.
- **Issue:** Inserting JSX in MDX caused Nextra to remove the applied styling and add its own, leading to the demo page not rendering correctly.

### Solution

- Create a standalone application for the demo site, without Nextra.
- Implementing this solution would take me about half a day. I just need approval to proceed.

## Way Forward

I plan to contribute more broadly to the project, but I wanted to start with these basics and get your feedback. I would love to hear your thoughts. If you have any questions or need further clarification, I am happy to provide additional information.

### CODE REVIEW

**Comment by contawo** [comment]
The changes are on the `docs` repository. I stored the old docs repository as `old-docs`.

**Comment by MohammadAbuMattar** [comment]
I'll check it first, and thanks for your hard work.

**Comment by MKAbuMattar** [comment]
I'll check it first, and thanks for your hard work. Also, please change the PR to the dev branch.

**Comment by contawo** [comment]
## Deployed
I have deployed it from my side so that you can see the live version.
Link: https://react-highlight-syntax-three.vercel.app/

**Comment by contawo** [comment]
I just changed the PR to the `dev` branch

**Comment by MKAbuMattar** [comment]
I checked it, and it looks good. However, please add `Designed by @contawo` in the footer section.

**Comment by contawo** [comment]
Are there any other changes that you would like me to make?

**Comment by MKAbuMattar** [comment]
No, that's it. After you make the changes, I'll merge the PR. Thanks for your offer to help.

**Pull request merged**
